# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f79a4cb8577c1145a6b3e900994dabfc3fe2e1258968b73740b38a77c3faa5fe9b01565fa34e13a949583b87bb7053531cfb150027046c6b18167cf19bcb586

test:
  secret_key_base: 13dc7e09e41c5f9c204ee218819d60fde1af313ae7e14271f27ff6b01c78c20ad29f1f549e21a82b47eaa1e43a21c057926e6a87f8f81643c78e074e3e67e4f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
